import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { db } from "@/lib/db";
import { SessionProvider } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await db.user
  console.log("User log : " +  user)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
        {children}
        </SessionProvider>
        </body>
    </html>
  );
}
